### ISSUE TITLE
[Request] Remove fast travel feature from Retreat skill 

### ISSUE THREAD

**Issue by firelad97** [JackitK/GoldenSun-QOL#1]
![IMG_0704](https://github.com/user-attachments/assets/079f9f14-d520-4596-8756-e022a6503119)
![IMG_0705](https://github.com/user-attachments/assets/0f6b1fac-6101-4a0e-99f9-5b95da622f96)

As seen above, the barricaded passage to Kolima is missing in this romhack. After researching, it appears that Retreat fast travel feature implemented in this romhack is the culprit.

I prefer to keep everything from original intact aside from QoL changes that I think this romhack will be great for, but removing a location entirely from the game just to use fast travel early on, is not for me.

Please remove this feature in the next update or find a way to keep the passage intact.

Thank you.

**Comment by JackitK** [comment]
There are currently no plans to update Golden Sun QOL as I am currently focused on other projects.

If I ever do come back to this and someone more experience than me in hacking Golden Sun is able to make and offer an alternative I will consider adding it.  As the fast travel code was taken from another project, I do not have the means to access and edit said code, as I do not have experience in the langue the fast travel code was made in.

Alternatives, like a version that removes fast travel all together, will be considered if this project is ever revisited. But currently I do not have plans to ever revisit this project.
